# Generated by Django 4.2.7 on 2023-12-08 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('all', 'Все'), ('food and drinks', 'Еда и Напитки'), ('beauty and health', 'Красота и Здоровье'), ('house and garden', 'Дом и Сад'), ('sports', 'Спорт'), ('clothing and accessories', 'Одежда и Аксессуары'), ('electronics and engineering', 'Электроника и Техника'), ('books, toys and hobbies', 'Книги, Игрушки и Хобби'), ('pets', 'Питомцы'), ('cars and transport', 'Авто и Транспорт'), ('floristry and gifts', 'Флористика и Подарки'), ('office supplies', 'Канцелярские Товары')], default='all', max_length=30),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Web_App.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Web_App.subcategory'),
        ),
    ]
