# Generated by Django 4.2.7 on 2023-12-12 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0002_remove_product_category_order_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='Web_App.category'),
        ),
    ]
