# Generated by Django 4.2.7 on 2023-12-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0007_alter_customuser_address_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='(Скидка в процентах)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('out_of_stock', 'Нет в наличии')], default='in_stock', max_length=15, null=True),
        ),
    ]
